homepage:
    path:     /
    defaults: { _controller: BatteryBundle:Statistic:index }

add:
    path:     /add
    defaults: { _controller: BatteryBundle:Statistic:add}

reset:
    path:     /reset
    defaults: { _controller: BatteryBundle:Statistic:reset}